//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 VegInfoSystem.rc 使用
//
#define DIG_MAINTAIN2                   9
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDD_CDisplayView                311
#define IDI_LIST                        313
#define IDI_IO                          315
#define IDI_LISTon                      316
#define IDI_MAINTAIN                    317
#define IDI_SEARCH                      319
#define IDI_SEARCHon                    320
#define IDI_STAT                        321
#define IDI_ICON9                       322
#define IDI_STATon                      322
#define IDI_CHECK                       323
#define IDI_CHECKon                     324
#define DIG_INFO                        325
#define DIG_MAINTIAN1                   327
#define DIG_MAINTAIN3                   331
#define DIG_SEARCH                      333
#define BNT_PATH                        335
#define DIG_STAT                        335
#define DIG_IO                          337
#define DIG_IO1                         337
#define DIG_INHELP                      340
#define DIG_IO2                         342
#define LIST_KIND                       1001
#define BUT_SHOW                        1003
#define IDC_BUTTON1                     1004
#define BNT_DEL                         1004
#define BNT_SECK                        1004
#define BNT_STAT2                       1004
#define BNT_IN                          1004
#define BNT_GET                         1004
#define LIST_VEG                        1006
#define EDIT_ADDNUM                     1006
#define LIST_PLANT                      1007
#define EDIT_ADDNAME                    1007
#define COMBO_NUM                       1008
#define EDIT_MODNAME                    1009
#define EDIT_MODNUM                     1010
#define BNT_ADD                         1011
#define BNT_ADDC                        1012
#define BNT_MOD                         1013
#define BNT_MODC                        1014
#define CMB_NUM                         1015
#define EDIT_NAME                       1016
#define EDIT_ADDNUT                     1017
#define EDIT_NAME2                      1017
#define EDIT_VNAME2                     1017
#define EDIT_MODNUT                     1018
#define EDIT_ADDNAME2                   1019
#define EDIT_ADDVNAME                   1019
#define CMB_NUM2                        1020
#define EDIT_MODNAME2                   1021
#define CMB_VNUM2                       1021
#define EDIT_MODVNAME                   1021
#define EDIT_NUM                        1022
#define EDIT_VNUM                       1022
#define CMB_ADDKNUM                     1024
#define CMB_MODKNUM                     1025
#define EDIT_ADDAREA                    1027
#define EDIT_ADDWIG                     1028
#define EDIT_ADDYEAR                    1029
#define EDIT_PNUM                       1030
#define IDC_COMBO1                      1031
#define CMB_PNUM                        1031
#define CMB_INMODE                      1031
#define CMB_KIND                        1031
#define IDC_EDIT5                       1032
#define EDIT_MODAREA                    1032
#define EDIT_SECVNUT                    1032
#define EDIT_OUTYEAR                    1032
#define EDIT_AREA1                      1032
#define IDC_EDIT6                       1033
#define EDIR_MODWIG                     1033
#define EDIT_SECPVNUM                   1033
#define EDIT_AREA2                      1033
#define IDC_EDIT7                       1034
#define EDIT_MODYEAR                    1034
#define EDIT_SECPYEAR                   1034
#define EDIT_WIG1                       1034
#define CMB_VNUM                        1035
#define EDIT_KNAME                      1036
#define EDIT_WIG2                       1036
#define EDIT_VNAME                      1037
#define LIST_SECVEG                     1039
#define LIST_SECPLANT                   1040
#define EDIT_SECKNUM                    1041
#define EDIT_SECVNAME                   1043
#define EDIT_SECVKIND                   1044
#define BNT_SECV1                       1045
#define BNT_SECV2                       1046
#define BNT_EPTV2                       1047
#define BNT_EPTV1                       1048
#define IDC_BUTTON6                     1049
#define BNT_SECP1                       1049
#define IDC_BUTTON7                     1050
#define BNT_EPTP1                       1050
#define IDC_EDIT8                       1051
#define EDIT_PVNAME                     1051
#define IDC_BUTTON8                     1052
#define BNT_SECP2                       1052
#define IDC_BUTTON9                     1053
#define BNT_EPTP2                       1053
#define BUT_EPTK                        1055
#define EDIT_STATYEAR1                  1058
#define EDIT_STATYEAR2                  1059
#define LIST_STAT1                      1064
#define EDIT_STATNUT                    1065
#define LIST_STAT3                      1066
#define LIST_STAT2                      1067
#define BNT_EPT2                        1068
#define BNT_STAT3                       1069
#define BNT_EPT3                        1070
#define RAD_IN1                         1071
#define RAD_IN2                         1072
#define RAD_IN3                         1073
#define EDIT_INPATH                     1074
#define BNT_INC                         1076
#define BNT_INHELP                      1078
#define EDIT_OUTPATH1                   1081
#define BNT_OUTPATH1                    1082
#define BNT_OUT1                        1083
#define BNT_GET1                        1084
#define LIST_OUT1                       1085
#define BNT_OEPT1                       1086
#define EDIT_OUTVNAME                   1088
#define LIST_OUT2                       1089
#define BNT_GET2                        1090
#define EDIT_OUTPATH2                   1091
#define BNT_OUTPATH2                    1092
#define BNT_OUT2                        1093
#define BNT_OEPT2                       1094
#define LIST_OUT                        1096
#define RAD_KIND                        1097
#define RAD_VEG                         1098
#define RAD_YEAR1                       1101
#define RAD_YEAR2                       1102
#define EDIT_YEAR1                      1104
#define EDIT_YEAR2                      1105
#define CHK_KNAME                       1106
#define CHK_VNAME                       1107
#define CHE_KNUM                        1108
#define CHK_NUT                         1109
#define CHK_AREA                        1110
#define CHK_WIG                         1111
#define CHK_YEAR                        1112
#define BNT_OUT                         1117
#define STA_KIND                        1118
#define STA_VNAME                       1119
#define STA_YEAR                        1120
#define IDC_CHECK1                      1125
#define CHK_ALL                         1125
#define IDC_CHECK2                      1126
#define BNT_OPT                         1127
#define EDIT_STATYEAR                   1128
#define BNT_STAT1                       1129
#define STA_STATYEAR                    1131
#define BNT_EPT1                        1132
#define BNT_STATTREND                   1133
#define STA_VTITLE                      1134
#define PIC_VEG                         1136
#define ID_Menu                         32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_32775                        32775
#define ID_32776                        32776
#define ID_32777                        32777
#define ID_32778                        32778
#define ID_32779                        32779
#define ID_32780                        32780
#define ID_32781                        32781
#define ID_ACCELERATOR32782             32782
#define MENU_INFO                       32784
#define MENU_MAINTAIN1                  32785
#define MENU_MAINTAIN2                  32786
#define MENU_MAINTAIN3                  32787
#define MENU_SEC                        32788
#define MENU_STAT                       32789
#define MENU_IO1                        32790
#define MENU_IO2                        32791

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        347
#define _APS_NEXT_COMMAND_VALUE         32794
#define _APS_NEXT_CONTROL_VALUE         1137
#define _APS_NEXT_SYMED_VALUE           312
#endif
#endif
